### ISSUE TITLE
Assembly STEP file format

### ISSUE THREAD

**Issue by yvanblanchard** [GenerativeMachine/Gen5X#1]
Hello,

Wonderful project!
Would it be possible to get access to the STEP assembly file, instead of STL mesh files ?
That would ease the building of the assembly in a CAD software (each part already positioned in context).
Moreover, it seems that there are some missing parts (STLs).

Thank you.

**Comment by glabifrons** [comment]
Agreed, a STEP would be extremely helpful in not only assembly, but for figuring out what parts are needed (since there's no BOM, issue #2).
It would also make it easier for the community to publish enhancements.

**Comment by GenerativeMachine** [comment]
Link to the Fusion360 model now posted on the README doc. This should give you full access to the model and let you download the files in a range of formats.     

https://a360.co/3Y41ZV0
