### ISSUE TITLE
Non printed parts

### ISSUE THREAD

**Issue by Knotas23** [GenerativeMachine/Gen5X#2]
Hello I would like to print and put together a working printer, but I dont know what I need to buy to I can complete this awesome printer. Can you upload non printed parts list please?

**Comment by FiveStrike** [comment]
Yeah a BOM would be imminently helpful!

**Comment by SventeHof** [comment]
a BOM would be more than helpful!

**Comment by glabifrons** [comment]
A BOM is definitely needed, or at least a STEP file (see #1) so we can figure it out.
The tight-zoomed video clips and pictures don't give nearly enough detail.

**Comment by GenerativeMachine** [comment]
Just uploaded the BOM and some exploded drawings for the V1.0
