### ISSUE TITLE
Hardware list

### ISSUE THREAD

**Issue by Ambro666** [GenerativeMachine/Gen5X#3]
How about a hardware list for the stl files. Motors, rods, gears, pulleys, etc, etc

**Comment by Knotas23** [comment]
I write it some days ago too. I write him email too And answer Is : (but Its all :-( )
![Screenshot_20230222-065601](https://user-images.githubusercontent.com/125441783/220535412-f782dc12-fad9-45fd-b01f-a073da2ffeaa.png)

**Comment by Ambro666** [comment]
this is great now I'll start the project.
    On Friday, February 24, 2023 at 01:38:09 PM PST, Generative Machine ***@***.***> wrote:  
 
 


Closed #3 as completed.
