### ISSUE TITLE
slicing

### ISSUE THREAD

**Issue by paysan1664** [GenerativeMachine/Gen5X#6]
Hello,

really nice projet, I could be interesting to build one machine. But one question, what about slicing? You mentioned Dotx but software is not available freely.

Only the trial gcode is available to test your gen5X?

Regards,

Nicolas

**Comment by GenerativeMachine** [comment]
There are some slicing options for non-planer/5 axis printing that are starting to become available for Rhino/Grasshopper. Have a look at the open5x project and their slicing tool, and also the nonplaner3d too here https://github.com/r3dsign/nonplanar3d
